{% set name = "Viscid" %}
{% set version = "1.0.0.dev10" %}
{% set file_ext = "tar.gz" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://github.com/viscid-hub/Viscid/archive/{{ version }}.{{ file_ext }}

build:
  skip: True  # [not x86_64]
  number: 0
  script: python setup.py install  # [not (win and py27)]
  script: python setup.py build & python setup.py build --compiler=mingw32 & python setup.py install  # [win and py27]

requirements:
  build:
    - {{ compiler('c') }}  # [win]
    - m2w64-gcc-fortran  # [win]
    - clang_osx-64  # [osx]
    - gfortran_osx-64  # [osx]
    - gcc_linux-64  # [linux]
    - gfortran_linux-64  # [linux]

  host:
    - python
    - setuptools
    - numpy =1.11  # [py27]
    - numpy >=1.14,<2.0a0  # [not py27]

  run:
    - python
    - numpy >=1.11,<2.0a0  # [py27]
    - numpy >=1.14,<2.0a0  # [not py27]
    - ipython
    - matplotlib >=1.4
    - pyqt
    - scipy
    - numexpr
    - h5py

test:
  imports:
    - viscid
    - viscid.calculator
    - viscid.compat
    - viscid.compat.futures
    - viscid.cython
    - viscid.plot
    - viscid.readers

about:
  home: https://github.com/viscid-hub/Viscid
  license: MIT License
  license_family: MIT
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE.txt'
  summary: Visualize data on structured meshes in python
  description: "Python framework to visualize scientific data on structured meshes."
  doc_url: 'https://viscid-hub.github.io/Viscid-docs/docs/master/index.html'
  dev_url: 'https://github.com/viscid-hub/Viscid'

extra:
  recipe-maintainers: 'viscid-hub'
