# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "fYZoEWW0xRQJncXJS1/xQcvFNp6P8gGqJmSlVHdphNPgY73nrWIu0aVLhaX+FHM+4Z4X+TN/KXMyiZjBqD65LRPQ98XWHv2xZ0DqgknerSZ0S5tKq6Fouq17BySnwIjVhEKhGOIX2G/26Bj5aFxAPlsnUrn/OIpEUuDec1NTJ8UMGOeAYRkbo2o2h4zhlizABb5BjvnfG2a6Kv3xXsl2p1fk8Uxzx0Vc9WFW+hXPWl8rLryWRPdabET89RLPNRgfNkEevNlUGcasFftTB8J4TYZHZCadln6VSSkuZ+a5QQ+wM9CIgzV5+AwPnk3NItxtElpV576znS1gReB7GcAk0QeIiR3RAVWd3TMEEFSNzQtZow4kAAr2F7JFOmLEx/yu4K7Y2Zp3QluhSq70/Kr13sTzNEN23L5cScp55beIM7lLhJkLFdb9HvrlERspvmnlOcDS0Rh571Y9U1XGTnwX/uFxulpjqffnof1lP5RbU22fUpO0LVCwCxlq7sUsbZqboWiC7Gng7jkW14IueXtM4Nu6LPU2FwAr+Q4UDLXzLq5at8icMgZWEk7A329TN8TRZLF4/tHsbxTJdjh1bLijnIjeA5nqBSMdLHQ4hHufrqzbUeRUhFWaar9eKXZLQOE0Rt7P4+ueC+jcFWp5VNAKWooZKhEcIP8vblLkeO2Wvh4="

matrix:
  include:
    - env: CONFIG=osx_python2.7 UPLOAD_PACKAGES=True PLATFORM=osx-64
      os: osx
      osx_image: xcode9.4

    - env: CONFIG=osx_python3.5 UPLOAD_PACKAGES=True PLATFORM=osx-64
      os: osx
      osx_image: xcode9.4

    - env: CONFIG=osx_python3.6 UPLOAD_PACKAGES=True PLATFORM=osx-64
      os: osx
      osx_image: xcode9.4

    - env: CONFIG=osx_python3.7 UPLOAD_PACKAGES=True PLATFORM=osx-64
      os: osx
      osx_image: xcode9.4

script:
  - export CI=travis
  - export GIT_BRANCH="$TRAVIS_BRANCH"

  # hack: download legacy OSX 10.9 sdk from github
  - |
    echo "Installing MacOSX10.9.sdk"
    SDK_MD5="de552e9a4ef12999d2e1f25acce51a76"
    SDK_SHA256="a7e52651ec33f0fc7fc025734365854f012875748ebe1a5d1cd8555c5a118ebd"
    echo "Downloading SDK"
    SDK_NAME="MacOSX10.9.sdk"
    curl -OfsSL https://gist.github.com/viscid-hub/f108b33bcbe4bf7d1b63cf76de4d435a/raw/MacOSX10.9.sdk.tar.bz2
    echo "Decompressing SDK"
    bzip2 --decompress --force ${SDK_NAME}.tar.bz2
    echo "Verifying SDK"
    dl_md5="$(openssl dgst -md5 ${SDK_NAME}.tar | awk '{print tolower($NF)}')"
    dl_sha256="$(openssl dgst -sha256 ${SDK_NAME}.tar | awk '{print tolower($NF)}')"
    if [ "${SDK_MD5}" != "${dl_md5}" ]; then
      echo "!!!! MacOSX10.9.sdk md5 hash mismatch !!!!"
      echo "expected hash    : ${SDK_MD5}"
      echo "hash of download : ${dl_md5}"
      exit 1
    fi
    if [ "${SDK_SHA256}" != "${dl_sha256}" ]; then
      echo "!!!! MacOSX10.9.sdk sha256 hash mismatch !!!!"
      echo "expected hash    : ${SDK_SHA256}"
      echo "hash of download : ${dl_sha256}"
      exit 1
    fi
    echo "Extracting SDK"
    tar -xf MacOSX10.9.sdk.tar
    echo "Moving SDK"
    sdk_dest="$(xcode-select -p)/Platforms/MacOSX.platform/Developer/SDKs"
    sudo mkdir -p ${sdk_dest}
    sudo mv MacOSX10.9.sdk ${sdk_dest}/
    export CONDA_BUILD_SYSROOT="${sdk_dest}/MacOSX10.9.sdk"

  - if [[ ${PLATFORM} =~ .*osx.* ]]; then ./.travis/run_osx_build.sh; fi
