# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "IzsWh3f6d6lBvww6Co5yHZPPq+2sdF0hMN2mxLXO/oiouX4CLcuCZQIs/YfadNfWI5jtKZ2n9Cg4UQFMonJIyHSPVGv/EzV9i2aF8Fo5CmITdXPur1wP+pOCD4BwCNCLgdz8C/Y9mAoY4KZdUDLPvnRlbK3i7d6eVeaJsy8vuKt3pYilJkDPb3dsuxtr78DC/SV559DU8RvIcpdikrcBplTvX0z5kpIT0jdunv7kUeF8+2v5DbH/wb6iN3DiOfjWLVqjL0VVE80wdKor0sWVyIgJsCNpXd/1xQWGSz76k6aREi2G2OQ/P4qTKh/dmmwhvpnO5p0ZfAd6Z5DEGCfvmHs3bl0f+GjcKf+dpvh5JQOLunbZgeB9s1VNQtK+RQNnh/T6BIXvm2+ViA2pgsOqylFz2r//8VVQvdcfhZbnjcUUjTqzq0L8Huk8P+24tILuzEt+LaR7UayC3x2+ZR/wkTb2DZ5/ge2BbgXVAokWPdNyuq69C6qIQl8txmb2bVvvFRlWDcdhoQmuV98JiOtl5U+BjzqJsdCODBfvwvY4BNWve5fHxBxubT0dH3I0BlMnlDxr6NXNcdXPPoatJjAYXVzhQdQaSEJaAbldndbWC/jTP97lYUYrstYowOpgmONTcyPjSWU1iERfWoier83pfumqU8AgXPrjw88ZNnG9/pM="

matrix:
  include:
    - env: CONFIG=osx_python2.7 UPLOAD_PACKAGES=True PLATFORM=osx-64
      os: osx
      osx_image: xcode9.4

    - env: CONFIG=osx_python3.5 UPLOAD_PACKAGES=True PLATFORM=osx-64
      os: osx
      osx_image: xcode9.4

    - env: CONFIG=osx_python3.6 UPLOAD_PACKAGES=True PLATFORM=osx-64
      os: osx
      osx_image: xcode9.4

    - env: CONFIG=osx_python3.7 UPLOAD_PACKAGES=True PLATFORM=osx-64
      os: osx
      osx_image: xcode9.4

script:
  - export CI=travis
  - export GIT_BRANCH="$TRAVIS_BRANCH"

  # hack: download legacy OSX 10.9 sdk from github
  - |
    echo "Installing MacOSX10.9.sdk"
    SDK_MD5="de552e9a4ef12999d2e1f25acce51a76"
    SDK_SHA256="a7e52651ec33f0fc7fc025734365854f012875748ebe1a5d1cd8555c5a118ebd"
    echo "Downloading SDK"
    SDK_NAME="MacOSX10.9.sdk"
    curl -OfsSL https://gist.github.com/viscid-hub/f108b33bcbe4bf7d1b63cf76de4d435a/raw/MacOSX10.9.sdk.tar.bz2
    echo "Decompressing SDK"
    bzip2 --decompress --force ${SDK_NAME}.tar.bz2
    echo "Verifying SDK"
    dl_md5="$(openssl dgst -md5 ${SDK_NAME}.tar | awk '{print tolower($NF)}')"
    dl_sha256="$(openssl dgst -sha256 ${SDK_NAME}.tar | awk '{print tolower($NF)}')"
    if [ "${SDK_MD5}" != "${dl_md5}" ]; then
      echo "!!!! MacOSX10.9.sdk md5 hash mismatch !!!!"
      echo "expected hash    : ${SDK_MD5}"
      echo "hash of download : ${dl_md5}"
      exit 1
    fi
    if [ "${SDK_SHA256}" != "${dl_sha256}" ]; then
      echo "!!!! MacOSX10.9.sdk sha256 hash mismatch !!!!"
      echo "expected hash    : ${SDK_SHA256}"
      echo "hash of download : ${dl_sha256}"
      exit 1
    fi
    echo "Extracting SDK"
    tar -xf MacOSX10.9.sdk.tar
    echo "Moving SDK"
    sdk_dest="$(xcode-select -p)/Platforms/MacOSX.platform/Developer/SDKs"
    sudo mkdir -p ${sdk_dest}
    sudo mv MacOSX10.9.sdk ${sdk_dest}/
    export CONDA_BUILD_SYSROOT="${sdk_dest}/MacOSX10.9.sdk"

  - if [[ ${PLATFORM} =~ .*osx.* ]]; then ./.travis/run_osx_build.sh; fi
