provider:
  linux: circle
  osx: travis
  win: appveyor
travis:
  secure:
    BINSTAR_TOKEN: "IzsWh3f6d6lBvww6Co5yHZPPq+2sdF0hMN2mxLXO/oiouX4CLcuCZQIs/YfadNfWI5jtKZ2n9Cg4UQFMonJIyHSPVGv/EzV9i2aF8Fo5CmITdXPur1wP+pOCD4BwCNCLgdz8C/Y9mAoY4KZdUDLPvnRlbK3i7d6eVeaJsy8vuKt3pYilJkDPb3dsuxtr78DC/SV559DU8RvIcpdikrcBplTvX0z5kpIT0jdunv7kUeF8+2v5DbH/wb6iN3DiOfjWLVqjL0VVE80wdKor0sWVyIgJsCNpXd/1xQWGSz76k6aREi2G2OQ/P4qTKh/dmmwhvpnO5p0ZfAd6Z5DEGCfvmHs3bl0f+GjcKf+dpvh5JQOLunbZgeB9s1VNQtK+RQNnh/T6BIXvm2+ViA2pgsOqylFz2r//8VVQvdcfhZbnjcUUjTqzq0L8Huk8P+24tILuzEt+LaR7UayC3x2+ZR/wkTb2DZ5/ge2BbgXVAokWPdNyuq69C6qIQl8txmb2bVvvFRlWDcdhoQmuV98JiOtl5U+BjzqJsdCODBfvwvY4BNWve5fHxBxubT0dH3I0BlMnlDxr6NXNcdXPPoatJjAYXVzhQdQaSEJaAbldndbWC/jTP97lYUYrstYowOpgmONTcyPjSWU1iERfWoier83pfumqU8AgXPrjw88ZNnG9/pM="
appveyor:
  secure:
    BINSTAR_TOKEN: /6Bo6FJkyuhPUKBDXEAz3BvnHMC220MaoLuiT2il7knzyOMvpT43Icz2VcsPK7lF
