provider:
  linux: circle
  osx: travis
  win: appveyor
travis:
  secure:
    BINSTAR_TOKEN: AuGJaS6Ug8/5P44G1Oya9n9cySMfnPiUX9KgpjmCM12fcN6emxRPRvyqcy3uo2rTmBn51Eu5GK7a+zDK24ODyhWhJIQgMlkisGvdNX+4VhWAjYZhIVOLgPCh8z+tPjV8SuYPJr9aHX7u8BucCDN6TKdCj9CU9/E2foCMKHllFHxm8noREaHfpClMg4ICH91XOGQ3tTLd3MqfOQaY4f2wD40utf4OOLfu4y8S9Ufc7Y0XKIOEtL4W7uq4QnfKhYHWkZLp/FV3W7Giq0Dz5ZjwConAWKtz63Q6LMkUzLmIw5wfAQ3QIBQaT/f70yuXufxwEdptDfdjGTOR5+MSiQOcDDC3BnD3G3oW4x1KjjKbJeDg3QSTlgB686tx1n1jTTzZHhYJmXg1S+FNhZX6DCZvczWr6mTanz+yymKzfp6l8lo4+usEc8QWtfsCo4fcJVF9GbO1QRAsIXY53lxb9nHZQxpqGjFkimiXmq/8l/ZfX0DiuLQ5w2LT+i/HDbWuT0yVgTdSgUp6ahxNx91GW47iSA+NHYB5BG6BvQ21e9orAbPdFAO0XU0tHw1d5OaWf3apa/ZSwh26V/cP1AJYIPc617G1T/SykVBtA8VZCP3emIO+baV1XrPpvG2sLRVMzi9+CH8PjWHaKbG1A3lAjs1ibLuqQr4SSzYcpZCuqasTZ8s=
appveyor:
  secure:
    BINSTAR_TOKEN: 9O82YEDOL2SqS1j6GkDUQSmIVgF8OhykUw5LfD9c6zZgHfswA6L3Kfmup+h/JcAB
