provider:
  linux: circle
  osx: travis
  win: appveyor
travis:
  secure:
    BINSTAR_TOKEN: "fYZoEWW0xRQJncXJS1/xQcvFNp6P8gGqJmSlVHdphNPgY73nrWIu0aVLhaX+FHM+4Z4X+TN/KXMyiZjBqD65LRPQ98XWHv2xZ0DqgknerSZ0S5tKq6Fouq17BySnwIjVhEKhGOIX2G/26Bj5aFxAPlsnUrn/OIpEUuDec1NTJ8UMGOeAYRkbo2o2h4zhlizABb5BjvnfG2a6Kv3xXsl2p1fk8Uxzx0Vc9WFW+hXPWl8rLryWRPdabET89RLPNRgfNkEevNlUGcasFftTB8J4TYZHZCadln6VSSkuZ+a5QQ+wM9CIgzV5+AwPnk3NItxtElpV576znS1gReB7GcAk0QeIiR3RAVWd3TMEEFSNzQtZow4kAAr2F7JFOmLEx/yu4K7Y2Zp3QluhSq70/Kr13sTzNEN23L5cScp55beIM7lLhJkLFdb9HvrlERspvmnlOcDS0Rh571Y9U1XGTnwX/uFxulpjqffnof1lP5RbU22fUpO0LVCwCxlq7sUsbZqboWiC7Gng7jkW14IueXtM4Nu6LPU2FwAr+Q4UDLXzLq5at8icMgZWEk7A329TN8TRZLF4/tHsbxTJdjh1bLijnIjeA5nqBSMdLHQ4hHufrqzbUeRUhFWaar9eKXZLQOE0Rt7P4+ueC+jcFWp5VNAKWooZKhEcIP8vblLkeO2Wvh4="
appveyor:
  secure:
    BINSTAR_TOKEN: /6Bo6FJkyuhPUKBDXEAz3BvnHMC220MaoLuiT2il7knzyOMvpT43Icz2VcsPK7lF
